/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitingRoomRouteImport } from './routes/waiting-room'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResultRouteImport } from './routes/result'
import { Route as OnlineLobbyRouteImport } from './routes/online-lobby'
import { Route as ModeRouteImport } from './routes/mode'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoadingRouteImport } from './routes/loading'
import { Route as GameRouteImport } from './routes/game'
import { Route as DeploymentRouteImport } from './routes/deployment'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WaitingRoomRoute = WaitingRoomRouteImport.update({
  id: '/waiting-room',
  path: '/waiting-room',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineLobbyRoute = OnlineLobbyRouteImport.update({
  id: '/online-lobby',
  path: '/online-lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeRoute = ModeRouteImport.update({
  id: '/mode',
  path: '/mode',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadingRoute = LoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentRoute = DeploymentRouteImport.update({
  id: '/deployment',
  path: '/deployment',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/deployment': typeof DeploymentRoute
  '/game': typeof GameRoute
  '/loading': typeof LoadingRoute
  '/login': typeof LoginRoute
  '/mode': typeof ModeRoute
  '/online-lobby': typeof OnlineLobbyRoute
  '/result': typeof ResultRoute
  '/settings': typeof SettingsRoute
  '/waiting-room': typeof WaitingRoomRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/deployment': typeof DeploymentRoute
  '/game': typeof GameRoute
  '/loading': typeof LoadingRoute
  '/login': typeof LoginRoute
  '/mode': typeof ModeRoute
  '/online-lobby': typeof OnlineLobbyRoute
  '/result': typeof ResultRoute
  '/settings': typeof SettingsRoute
  '/waiting-room': typeof WaitingRoomRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/deployment': typeof DeploymentRoute
  '/game': typeof GameRoute
  '/loading': typeof LoadingRoute
  '/login': typeof LoginRoute
  '/mode': typeof ModeRoute
  '/online-lobby': typeof OnlineLobbyRoute
  '/result': typeof ResultRoute
  '/settings': typeof SettingsRoute
  '/waiting-room': typeof WaitingRoomRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/deployment'
    | '/game'
    | '/loading'
    | '/login'
    | '/mode'
    | '/online-lobby'
    | '/result'
    | '/settings'
    | '/waiting-room'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/deployment'
    | '/game'
    | '/loading'
    | '/login'
    | '/mode'
    | '/online-lobby'
    | '/result'
    | '/settings'
    | '/waiting-room'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/deployment'
    | '/game'
    | '/loading'
    | '/login'
    | '/mode'
    | '/online-lobby'
    | '/result'
    | '/settings'
    | '/waiting-room'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DeploymentRoute: typeof DeploymentRoute
  GameRoute: typeof GameRoute
  LoadingRoute: typeof LoadingRoute
  LoginRoute: typeof LoginRoute
  ModeRoute: typeof ModeRoute
  OnlineLobbyRoute: typeof OnlineLobbyRoute
  ResultRoute: typeof ResultRoute
  SettingsRoute: typeof SettingsRoute
  WaitingRoomRoute: typeof WaitingRoomRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waiting-room': {
      id: '/waiting-room'
      path: '/waiting-room'
      fullPath: '/waiting-room'
      preLoaderRoute: typeof WaitingRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-lobby': {
      id: '/online-lobby'
      path: '/online-lobby'
      fullPath: '/online-lobby'
      preLoaderRoute: typeof OnlineLobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mode': {
      id: '/mode'
      path: '/mode'
      fullPath: '/mode'
      preLoaderRoute: typeof ModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loading': {
      id: '/loading'
      path: '/loading'
      fullPath: '/loading'
      preLoaderRoute: typeof LoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployment': {
      id: '/deployment'
      path: '/deployment'
      fullPath: '/deployment'
      preLoaderRoute: typeof DeploymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DeploymentRoute: DeploymentRoute,
  GameRoute: GameRoute,
  LoadingRoute: LoadingRoute,
  LoginRoute: LoginRoute,
  ModeRoute: ModeRoute,
  OnlineLobbyRoute: OnlineLobbyRoute,
  ResultRoute: ResultRoute,
  SettingsRoute: SettingsRoute,
  WaitingRoomRoute: WaitingRoomRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
